### ISSUE TITLE
Can the schema https://www.w3.org/2007/schema-for-xslt20.xsd for XSLT 2.0 be added to the resolver data?

### ISSUE THREAD

**Issue by martin-honnen** [xmlresolver/xmlresolverdata#1]
I see that the XML resolver data has the XSD 1.1 schema for XSLT 3 but the XSD 1.0 schema for XSLT 2 (which is at https://www.w3.org/2007/schema-for-xslt20.xsd and is defined in the spec at https://www.w3.org/TR/xslt20/#schema-for-xslt) seems to be missing.
Could it be added to the resolver data assembly?

**Comment by ndw** [comment]
Yep.
